//Boilerplate stuffs
var express = require('express');
var app = express();
var handlebars = require('express-handlebars');

app.use(express.static('public'));
app.engine('handlebars', handlebars());
app.set('view engine', 'handlebars');
app.set('port', 4512);

// Setup for the random pokemon Generator
pokemonHash = {1:{
  'name':'Bulbasaur',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif',
  'link':'https://pokemondb.net/pokedex/bulbasaur'},
  2:{
  'name':'Ivysaur',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif',
  'link':'https://pokemondb.net/pokedex/ivysaur'},
  3:{
  'name':'Venusaur',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif',
  'link':'https://pokemondb.net/pokedex/venusaur'},
  4:{
  'name':'Charmander',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif',
  'link':'https://pokemondb.net/pokedex/charmander'},
  5:{
  'name':'Charmeleon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif',
  'link':'https://pokemondb.net/pokedex/charmeleon'},
  6:{
  'name':'Charizard',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif',
  'link':'https://pokemondb.net/pokedex/charizard'},
  7:{
  'name':'Squirtle',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif',
  'link':'https://pokemondb.net/pokedex/squirtle'},
  8:{
  'name':'Wartortle',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif',
  'link':'https://pokemondb.net/pokedex/wartortle'},
  9:{
  'name':'Blastoise',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif',
  'link':'https://pokemondb.net/pokedex/blastoise'},
  10:{
  'name':'Caterpie',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif',
  'link':'https://pokemondb.net/pokedex/caterpie'},
  11:{
  'name':'Metapod',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif',
  'link':'https://pokemondb.net/pokedex/metapod'},
  12:{
  'name':'Butterfree',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif',
  'link':'https://pokemondb.net/pokedex/butterfree'},
  13:{
  'name':'Weedle',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif',
  'link':'https://pokemondb.net/pokedex/weedle'},
  14:{
  'name':'Kakuna',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif',
  'link':'https://pokemondb.net/pokedex/kakuna'},
  15:{
  'name':'Beedrill',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif',
  'link':'https://pokemondb.net/pokedex/beedrill'},
  16:{
  'name':'Pidgey',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif',
  'link':'https://pokemondb.net/pokedex/pidgey'},
  17:{
  'name':'Pidgeotto',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif',
  'link':'https://pokemondb.net/pokedex/pidgeotto'},
  18:{
  'name':'Pidgeot',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif',
  'link':'https://pokemondb.net/pokedex/pidgeot'},
  19:{
  'name':'Rattata',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif',
  'link':'https://pokemondb.net/pokedex/rattata'},
  20:{
  'name':'Raticate',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif',
  'link':'https://pokemondb.net/pokedex/raticate'},
  21:{
  'name':'Spearow',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif',
  'link':'https://pokemondb.net/pokedex/spearow'},
  22:{
  'name':'Fearow',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif',
  'link':'https://pokemondb.net/pokedex/fearow'},
  23:{
  'name':'Ekans',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif',
  'link':'https://pokemondb.net/pokedex/ekans'},
  24:{
  'name':'Arbok',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif',
  'link':'https://pokemondb.net/pokedex/arbok'},
  25:{
  'name':'Pikachu',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif',
  'link':'https://pokemondb.net/pokedex/pikachu'},
  26:{
  'name':'Raichu',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif',
  'link':'https://pokemondb.net/pokedex/raichu'},
  27:{
  'name':'Sandsrew',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/sandhrew.gif',
  'link':'https://pokemondb.net/pokedex/sandshrew'},
  28:{
  'name':'Sandslash',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif',
  'link':'https://pokemondb.net/pokedex/sandslash'},
  30:{
  'name':'Nidorina',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif',
  'link':'https://pokemondb.net/pokedex/nidorina'},
  31:{
  'name':'Nidoqueen',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif',
  'link':'https://pokemondb.net/pokedex/nidoqueen'},
  33:{
  'name':'Nidorino',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif',
  'link':'https://pokemondb.net/pokedex/nidorino'},
  34:{
  'name':'Nidoking',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif',
  'link':'https://pokemondb.net/pokedex/nidoking'},
  35:{
  'name':'Clefairy',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif',
  'link':'https://pokemondb.net/pokedex/clefairy'},
  36:{
  'name':'Clefable',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif',
  'link':'https://pokemondb.net/pokedex/clefable'},
  37:{
  'name':'vulpix',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif',
  'link':'https://pokemondb.net/pokedex/vulpix'},
  38:{
  'name':'Ninetales',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif',
  'link':'https://pokemondb.net/pokedex/ninetales'},
  39:{
  'name':'Jigglypuff',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif',
  'link':'https://pokemondb.net/pokedex/jigglypuff'},
  40:{
  'name':'Wigglytuff',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif',
  'link':'https://pokemondb.net/pokedex/wigglytuff'},
  41:{
  'name':'Zubat',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif',
  'link':'https://pokemondb.net/pokedex/zubat'},
  42:{
  'name':'Golbat',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif',
  'link':'https://pokemondb.net/pokedex/golbat'},
  43:{
  'name':'Oddish',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif',
  'link':'https://pokemondb.net/pokedex/oddish'},
  44:{
  'name':'Gloom',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif',
  'link':'https://pokemondb.net/pokedex/gloom'},
  45:{
  'name':'Vileplume',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif',
  'link':'https://pokemondb.net/pokedex/vileplume'},
  46:{
  'name':'Paras',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif',
  'link':'https://pokemondb.net/pokedex/paras'},
  47:{
  'name':'Parasect',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif',
  'link':'https://pokemondb.net/pokedex/parasect'},
  48:{
  'name':'Venonat',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif',
  'link':'https://pokemondb.net/pokedex/venonat'},
  49:{
  'name':'venomoth',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif',
  'link':'https://pokemondb.net/pokedex/venomoth'},
  50:{
  'name':'Diglett',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif',
  'link':'https://pokemondb.net/pokedex/diglett'},
  51:{
  'name':'Dugtrio',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif',
  'link':'https://pokemondb.net/pokedex/dugtrio'},
  52:{
  'name':'Meowth',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif',
  'link':'https://pokemondb.net/pokedex/meowth'},
  53:{
  'name':'Persian',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif',
  'link':'https://pokemondb.net/pokedex/persian'},
  54:{
  'name':'Psyduck',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif',
  'link':'https://pokemondb.net/pokedex/psyduck'},
  55:{
  'name':'Golduck',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif',
  'link':'https://pokemondb.net/pokedex/golduck'},
  56:{
  'name':'Mankey',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif',
  'link':'https://pokemondb.net/pokedex/mankey'},
  57:{
  'name':'Primeape',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif',
  'link':'https://pokemondb.net/pokedex/primeape'},
  58:{
  'name':'Growlithe',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif',
  'link':'https://pokemondb.net/pokedex/growlithe'},
  59:{
  'name':'Arcanine',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif',
  'link':'https://pokemondb.net/pokedex/arcanine'},
  60:{
  'name':'Poliwag',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif',
  'link':'https://pokemondb.net/pokedex/poliwag'},
  61:{
  'name':'Poliwhirl',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif',
  'link':'https://pokemondb.net/pokedex/poliwhirl'},
  62:{
  'name':'Poliwrath',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif',
  'link':'https://pokemondb.net/pokedex/poliwrath'},
  63:{
  'name':'Abra',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif',
  'link':'https://pokemondb.net/pokedex/abra'},
  64:{
  'name':'Kadabra',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif',
  'link':'https://pokemondb.net/pokedex/kadabra'},
  65:{
  'name':'Alakazam',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif',
  'link':'https://pokemondb.net/pokedex/alakazam'},
  66:{
  'name':'Machop',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif',
  'link':'https://pokemondb.net/pokedex/machop'},
  67:{
  'name':'Machoke',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif',
  'link':'https://pokemondb.net/pokedex/machoke'},
  68:{
  'name':'Machamp',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif',
  'link':'https://pokemondb.net/pokedex/machamp'},
  69:{
  'name':'Bellsprout',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif',
  'link':'https://pokemondb.net/pokedex/bellsprout'},
  70:{
  'name':'Weepinbell',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif',
  'link':'https://pokemondb.net/pokedex/weepinbell'},
  71:{
  'name':'Victreebel',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif',
  'link':'https://pokemondb.net/pokedex/victreebel'},
  72:{
  'name':'Tentacool',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacool.gif',
  'link':'https://pokemondb.net/pokedex/tentacool'},
  73:{
  'name':'Tentacruel',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/tentacruel.gif',
  'link':'https://pokemondb.net/pokedex/tentacruel'},
  74:{
  'name':'Geodude',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif',
  'link':'https://pokemondb.net/pokedex/geodude'},
  75:{
  'name':'Graveler',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif',
  'link':'https://pokemondb.net/pokedex/graveler'},
  76:{
  'name':'Golem',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif',
  'link':'https://pokemondb.net/pokedex/golem'},
  77:{
  'name':'Ponyta',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif',
  'link':'https://pokemondb.net/pokedex/ponyta'},
  78:{
  'name':'Rapidash',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif',
  'link':'https://pokemondb.net/pokedex/rapidash'},
  79:{
  'name':'Slowpoke',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif',
  'link':'https://pokemondb.net/pokedex/slowpoke'},
  80:{
  'name':'Slowbro',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif',
  'link':'https://pokemondb.net/pokedex/slowbro'},
  81:{
  'name':'Magnemite',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif',
  'link':'https://pokemondb.net/pokedex/magnemite'},
  82:{
  'name':'Magneton',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif',
  'link':'https://pokemondb.net/pokedex/magneton'},
  83:{
  'name':"Farfetch'd",
  'image':"https://img.pokemondb.net/sprites/black-white/anim/normal/farfetch'd.gif",
  'link':"https://pokemondb.net/pokedex/farfetch'd"},
  84:{
  'name':'Doduo',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif',
  'link':'https://pokemondb.net/pokedex/doduo'},
  85:{
  'name':'Dodrio',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif',
  'link':'https://pokemondb.net/pokedex/dodrio'},
  86:{
  'name':'Seel',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif',
  'link':'https://pokemondb.net/pokedex/seel'},
  87:{
  'name':'Dewgong',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif',
  'link':'https://pokemondb.net/pokedex/dewgong'},
  88:{
  'name':'Grimer',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif',
  'link':'https://pokemondb.net/pokedex/grimer'},
  89:{
  'name':'Muk',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif',
  'link':'https://pokemondb.net/pokedex/muk'},
  90:{
  'name':'Shellder',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif',
  'link':'https://pokemondb.net/pokedex/shellder'},
  91:{
  'name':'Cloyster',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif',
  'link':'https://pokemondb.net/pokedex/cloyster'},
  92:{
  'name':'Gastly',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif',
  'link':'https://pokemondb.net/pokedex/gastly'},
  93:{
  'name':'Haunter',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif',
  'link':'https://pokemondb.net/pokedex/haunter'},
  94:{
  'name':'Gengar',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif',
  'link':'https://pokemondb.net/pokedex/gengar'},
  95:{
  'name':'Onix',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif',
  'link':'https://pokemondb.net/pokedex/onix'},
  96:{
  'name':'Drowzee',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif',
  'link':'https://pokemondb.net/pokedex/drowzee'},
  97:{
  'name':'Hypno',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif',
  'link':'https://pokemondb.net/pokedex/hypno'},
  98:{
  'name':'Krabby',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif',
  'link':'https://pokemondb.net/pokedex/krabby'},
  99:{
  'name':'Kingler',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif',
  'link':'https://pokemondb.net/pokedex/kingler'},
  100:{
  'name':'Voltorb',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif',
  'link':'https://pokemondb.net/pokedex/voltorb'},
  101:{
  'name':'Electrode',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif',
  'link':'https://pokemondb.net/pokedex/electrode'},
  102:{
  'name':'Exeggcute',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif',
  'link':'https://pokemondb.net/pokedex/exeggcute'},
  103:{
  'name':'Exeggutor',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif',
  'link':'https://pokemondb.net/pokedex/exeggutor'},
  104:{
  'name':'Cubone',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif',
  'link':'https://pokemondb.net/pokedex/cubone'},
  105:{
  'name':'Marowak',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif',
  'link':'https://pokemondb.net/pokedex/marowak'},
  106:{
  'name':'Hitmonlee',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif',
  'link':'https://pokemondb.net/pokedex/hitmonlee'},
  107:{
  'name':'Hitmonchan',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif',
  'link':'https://pokemondb.net/pokedex/hitmonchan'},
  108:{
  'name':'Lickitung',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif',
  'link':'https://pokemondb.net/pokedex/lickitung'},
  109:{
  'name':'Koffing',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif',
  'link':'https://pokemondb.net/pokedex/koffing'},
  110:{
  'name':'Weezing',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif',
  'link':'https://pokemondb.net/pokedex/weezing'},
  111:{
  'name':'Rhyhorn',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif',
  'link':'https://pokemondb.net/pokedex/rhyhorn'},
  112:{
  'name':'Rhydon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif',
  'link':'https://pokemondb.net/pokedex/rhydon'},
  113:{
  'name':'Chansey',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif',
  'link':'https://pokemondb.net/pokedex/chansey'},
  114:{
  'name':'Tangela',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif',
  'link':'https://pokemondb.net/pokedex/tangela'},
  115:{
  'name':'Kangaskhan',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif',
  'link':'https://pokemondb.net/pokedex/kangaskhan'},
  116:{
  'name':'Horsea',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif',
  'link':'https://pokemondb.net/pokedex/horsea'},
  117:{
  'name':'seadra',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif',
  'link':'https://pokemondb.net/pokedex/seadra'},
  118:{
  'name':'Goldeen',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif',
  'link':'https://pokemondb.net/pokedex/goldeen'},
  119:{
  'name':'Seaking',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif',
  'link':'https://pokemondb.net/pokedex/seaking'},
  120:{
  'name':'Staryu',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif',
  'link':'https://pokemondb.net/pokedex/staryu'},
  121:{
  'name':'Starmie',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif',
  'link':'https://pokemondb.net/pokedex/starmie'},
  122:{
  'name':'Mr-mime',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/mr-mime.gif',
  'link':'https://pokemondb.net/pokedex/mr-mime'},
  123:{
  'name':'Scyther',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif',
  'link':'https://pokemondb.net/pokedex/scyther'},
  124:{
  'name':'Jynx',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif',
  'link':'https://pokemondb.net/pokedex/jynx'},
  125:{
  'name':'Electabuzz',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif',
  'link':'https://pokemondb.net/pokedex/electabuzz'},
  126:{
  'name':'Magmar',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif',
  'link':'https://pokemondb.net/pokedex/magmar'},
  127:{
  'name':'Pinsir',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif',
  'link':'https://pokemondb.net/pokedex/pinsir'},
  128:{
  'name':'Tauros',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif',
  'link':'https://pokemondb.net/pokedex/tauros'},
  129:{
  'name':'Magikarp',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif',
  'link':'https://pokemondb.net/pokedex/magikarp'},
  130:{
  'name':'Gyarados',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif',
  'link':'https://pokemondb.net/pokedex/gyarados'},
  131:{
  'name':'Lapras',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif',
  'link':'https://pokemondb.net/pokedex/lapras'},
  132:{
  'name':'Ditto',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif',
  'link':'https://pokemondb.net/pokedex/ditto'},
  133:{
  'name':'Eevee',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif',
  'link':'https://pokemondb.net/pokedex/eevee'},
  134:{
  'name':'Vaporeon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif',
  'link':'https://pokemondb.net/pokedex/vaporeon'},
  135:{
  'name':'Jolteon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif',
  'link':'https://pokemondb.net/pokedex/jolteon'},
  136:{
  'name':'Flareon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif',
  'link':'https://pokemondb.net/pokedex/flareon'},
  137:{
  'name':'Porygon',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif',
  'link':'https://pokemondb.net/pokedex/porygon'},
  138:{
  'name':'Omanyte',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif',
  'link':'https://pokemondb.net/pokedex/omanyte'},
  139:{
  'name':'Omastar',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif',
  'link':'https://pokemondb.net/pokedex/omastar'},
  140:{
  'name':'Kabuto',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif',
  'link':'https://pokemondb.net/pokedex/kabuto'},
  141:{
  'name':'Kabutops',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif',
  'link':'https://pokemondb.net/pokedex/kabutops'},
  142:{
  'name':'Aerodactyl',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif',
  'link':'https://pokemondb.net/pokedex/aerodactyl'},
  143:{
  'name':'Snorlax',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif',
  'link':'https://pokemondb.net/pokedex/snorlax'},
  144:{
  'name':'Aritcuno',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif',
  'link':'https://pokemondb.net/pokedex/articuno'},
  145:{
  'name':'Zapdos',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif',
  'link':'https://pokemondb.net/pokedex/zapdos'},
  146:{
  'name':'Moltres',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif',
  'link':'https://pokemondb.net/pokedex/moltres'},
  147:{
  'name':'Dratini',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif',
  'link':'https://pokemondb.net/pokedex/dratini'},
  148:{
  'name':'Dragonair',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif',
  'link':'https://pokemondb.net/pokedex/dragonair'},
  149:{
  'name':'Dragonite',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif',
  'link':'https://pokemondb.net/pokedex/dragonite'},
  150:{
  'name':'Mewtwo',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif',
  'link':'https://pokemondb.net/pokedex/mewtwo'},
  151:{
  'name':'Mew',
  'image':'https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif',
  'link':'https://pokemondb.net/pokedex/mew'},
}


// Routing
app.get('/', function(req, res){
  var context = {};

  // The Pokemon information
  context.pokemon1 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon2 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon3 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon4 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon5 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon6 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon7 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon8 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon9 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]
  context.pokemon10 = pokemonHash[Math.floor(Math.random() * (Object.keys(pokemonHash).length) + 1)]

  context.style = 'css/homePage.css'
  res.render('home', context);
});

app.get('/favorites', function(req, res){
  var context = {};

  context.style = 'css/favorites.css'
  res.render('favorites', context);
});

app.get('/about', function(req, res){
  var context = {};

  context.style = 'css/about.css'
  res.render('about', context);
});

app.get('/contact', function(req, res){
  var context = {};

  context.style = 'css/contact.css'
  res.render('contact', context);
});


app.listen(app.get('port'), function(){
  console.log('Serving is starting at port', app.get('port'));
});
